In [3]:
import pandas as pd
import numpy as np

### Convert the end-game dataset

In [4]:
df1 = pd.read_csv('c4_game_database.csv')
df1

pos_01  pos_02  pos_03  pos_04  pos_05  pos_06  pos_07  pos_08  \
0          1.0     1.0     1.0    -1.0    -1.0     1.0     0.0    -1.0   
1          0.0     0.0     1.0     1.0     1.0     1.0     0.0     0.0   
2          0.0     1.0     0.0     1.0     0.0     0.0     0.0     0.0   
3          0.0     0.0     0.0     1.0     0.0     0.0     0.0     0.0   
4          0.0    -1.0    -1.0    -1.0     1.0     0.0     0.0     1.0   
...        ...     ...     ...     ...     ...     ...     ...     ...   
376635     0.0     0.0     0.0    -1.0     0.0     0.0     0.0     0.0   
376636     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
376637     0.0     0.0     1.0     0.0     0.0     1.0     0.0     0.0   
376638     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
376639     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

        pos_09  pos_10  ...  pos_34  pos_35  pos_36  pos_37  pos_38  pos_39  \
0         -1.0    -1.0  ...     1.0     1.0    -1.0     1.0    -1.0     1.0   
1          0.0     1.0  ...    -1.0     1.0     1.0    -1.0    -1.0    -1.0   
2         -1.0     0.0  ...     0.0    -1.0     1.0    -1.0    -1.0     1.0   
3          0.0     0.0  ...     0.0     1.0     1.0     1.0    -1.0     1.0   
4          1.0     1.0  ...     0.0     1.0    -1.0    -1.0     1.0    -1.0   
...        ...     ...  ...     ...     ...     ...     ...     ...     ...   
376635     0.0    -1.0  ...     0.0     1.0    -1.0    -1.0    -1.0     1.0   
376636     0.0    -1.0  ...     0.0     0.0     0.0    -1.0     1.0    -1.0   
376637     0.0    -1.0  ...     1.0     1.0    -1.0    -1.0    -1.0     1.0   
376638    -1.0     0.0  ...    -1.0     0.0    -1.0    -1.0     1.0     1.0   
376639     0.0     0.0  ...    -1.0     0.0    -1.0    -1.0    -1.0     1.0   

        pos_40  pos_41  pos_42  winner  
0         -1.0     1.0    -1.0    -1.0  
1          1.0     1.0    -1.0     1.0  
2         -1.0    -1.0    -1.0    -1.0  
3         -1.0     0.0     1.0    -1.0  
4          1.0     0.0    -1.0     1.0  
...        ...     ...     ...     ...  
376635    -1.0     0.0     1.0    -1.0  
376636     1.0     0.0     0.0    -1.0  
376637     1.0     1.0    -1.0    -1.0  
376638     1.0    -1.0     0.0    -1.0  
376639    -1.0     1.0    -1.0     1.0  

[376640 rows x 43 columns]

In [5]:
df1.values[:, :-1]

array([[ 1.,  1.,  1., ..., -1.,  1., -1.],
       [ 0.,  0.,  1., ...,  1.,  1., -1.],
       [ 0.,  1.,  0., ..., -1., -1., -1.],
       ...,
       [ 0.,  0.,  1., ...,  1.,  1., -1.],
       [ 0.,  0.,  0., ...,  1., -1.,  0.],
       [ 0.,  0.,  0., ..., -1.,  1., -1.]])

In [26]:
# convert to our flattened format
def convert_df1(v):
    # v is flattened 1.0/-1.0 input, output is 1/0 flattened board rep that .reshape(6, 7, 2) would give the correct board
    return np.moveaxis(np.flip(np.hstack([v == 1.0, v == -1]).astype(int).reshape((2, 6, 7)), axis=1), 0, 2).flatten()


df1_ = pd.DataFrame(data={
    'board': df1.apply(lambda x: convert_df1(x.values[:-1]), axis=1),
    'target': df1.apply(lambda x: (x['winner'] + 1) / 2, axis=1)       # make [1, 0, 1] to [0, 0.5, 1]
})
df1_

board  target
0       [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, ...     0.0
1       [1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, ...     1.0
2       [1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, ...     0.0
3       [1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, ...     0.0
4       [0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, ...     1.0
...                                                   ...     ...
376635  [0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, ...     0.0
376636  [0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, ...     0.0
376637  [0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, ...     0.0
376638  [0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, ...     0.0
376639  [0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, ...     1.0

[376640 rows x 2 columns]

In [27]:
df1_.shape

(376640, 2)

In [32]:
# wins, draws, losses
df1_[df1_['target'] == 1].count()[0], df1_[df1_['target'] == 0.5].count()[0], df1_[df1_['target'] == 0].count()[0]

(181255, 14497, 180867)

In [28]:
# check ok
df1_.iloc[0]['board'].reshape(6, 7, 2).sum(axis=-1)

array([[1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 0]])

In [8]:
# np.flip(df1.iloc[0][:-1].values.reshape((6, 7)), axis=0)

In [9]:
# v = df1.iloc[0][:-1].values
# v

In [10]:
# np.flip(np.hstack([v == 1.0, v == -1]).astype(int).reshape((2, 6, 7)), axis=1)

### Convert the 8-ply dataset

In [17]:
df2 = pd.read_csv('connect-4.data')
df2

b b.1 b.2 b.3 b.4 b.5 b.6 b.7 b.8 b.9  ... b.25 b.26 b.27 b.28 b.29  \
0      b   b   b   b   b   b   b   b   b   b  ...    b    b    b    b    b   
1      b   b   b   b   b   b   o   b   b   b  ...    b    b    b    b    b   
2      b   b   b   b   b   b   b   b   b   b  ...    b    b    b    b    b   
3      o   b   b   b   b   b   b   b   b   b  ...    b    b    b    b    b   
4      b   b   b   b   b   b   b   b   b   b  ...    b    b    b    o    b   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...   
67551  x   x   b   b   b   b   o   x   o   b  ...    b    b    b    o    o   
67552  x   x   b   b   b   b   o   b   b   b  ...    b    b    b    o    x   
67553  x   x   b   b   b   b   o   o   b   b  ...    b    b    b    o    x   
67554  x   o   b   b   b   b   o   b   b   b  ...    b    b    b    o    x   
67555  x   o   o   o   x   b   o   b   b   b  ...    b    b    b    x    b   

      b.30 b.31 b.32 b.33   win  
0        b    b    b    b   win  
1        b    b    b    b   win  
2        b    b    b    b   win  
3        b    b    b    b   win  
4        b    b    b    b   win  
...    ...  ...  ...  ...   ...  
67551    x    b    b    b  loss  
67552    o    o    x    b  draw  
67553    x    o    b    b  loss  
67554    o    x    x    b  draw  
67555    b    b    b    b  draw  

[67556 rows x 43 columns]

In [18]:
df2.iloc[0, :-1].values.reshape((6, 7), order='F')

array([['b', 'b', 'x', 'x', 'o', 'b', 'b'],
       ['b', 'b', 'b', 'o', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'x', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'o', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'x', 'b', 'b', 'b'],
       ['b', 'b', 'b', 'o', 'b', 'b', 'b']], dtype=object)

In [25]:
v = df2.iloc[0, :-1]
z = np.hstack([v == 'x', v == 'o']).astype(int).reshape((6, 7, 2), order='F')
z[:, :, 0] - z[:, :, 1]

array([[ 0,  0,  1,  1, -1,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0],
       [ 0,  0,  0,  1,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0]])

In [33]:
# convert to our flattened format
def convert_df2(v):
    # v is flattened 1.0/-1.0 input, output is 1/0 flattened board rep that .reshape(6, 7, 2) would give the correct board
    return np.hstack([v == 'x', v == 'o']).astype(int).reshape((6, 7, 2), order='F').flatten()


df2_ = pd.DataFrame(data={
    'board': df2.apply(lambda x: convert_df2(x.values[:-1]), axis=1),
    'target': df2.apply(lambda x: (1.0 if x['win'] == 'win' else (0.5 if x['win'] == 'draw' else 0.0)), axis=1)
})
df2_

board  target
0      [0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, ...     1.0
1      [0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...     1.0
2      [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, ...     1.0
3      [0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ...     1.0
4      [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, ...     1.0
...                                                  ...     ...
67551  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...     0.0
67552  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...     0.5
67553  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...     0.0
67554  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...     0.5
67555  [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...     0.5

[67556 rows x 2 columns]

In [34]:
# wins, draws, losses
df2_[df2_['target'] == 1].count()[0], df2_[df2_['target'] == 0.5].count()[0], df2_[df2_['target'] == 0].count()[0]

(44472, 6449, 16635)

### Combine 

In [37]:
final_df = pd.concat([df1_, df2_])
final_df

board  target
0      [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, ...     0.0
1      [1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, ...     1.0
2      [1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, ...     0.0
3      [1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, ...     0.0
4      [0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, ...     1.0
...                                                  ...     ...
67551  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...     0.0
67552  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...     0.5
67553  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...     0.0
67554  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...     0.5
67555  [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...     0.5

[444196 rows x 2 columns]

In [38]:
final_df.to_hdf('my_c4_dataset.h5', key='c4_dataset', index=False)

C:\Users\mikem\AppData\Local\Temp\ipykernel_17884\1901246746.py:1: PerformanceWarning: 
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed,key->block0_values] [items->Index(['board'], dtype='object')]

  final_df.to_hdf('my_c4_dataset.h5', key='c4_dataset', index=False)


In [39]:
pd.read_hdf('my_c4_dataset.h5')

board  target
0      [0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, ...     0.0
1      [1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, ...     1.0
2      [1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, ...     0.0
3      [1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, ...     0.0
4      [0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, ...     1.0
...                                                  ...     ...
67551  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...     0.0
67552  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...     0.5
67553  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, ...     0.0
67554  [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ...     0.5
67555  [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ...     0.5

[444196 rows x 2 columns]